spring:
  profiles:
    active:  ${PROFILE:dev}
  application:
    name: "Sistema de Gestao SOS Animais"
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
server:
  port: ${SERVER_PORT:8081}
  forward-headers-strategy: FRAMEWORK
  servlet:
    context-path: /api
keycloak:
  url: ${KEYCLOACK_URL_AUTH:http://localhost:8080/realms/sosanimais-realm/protocol/openid-connect/auth}
  token:
    url: ${KEYCLOACK_TOKEN_URL:http://localhost:8080/realms/sosanimais-realm/protocol/openid-connect/token}
  logout:
    url: ${KEYCLOACK_LOGOUT_URL:http://localhost:8080/realms/sosanimais-realm/protocol/openid-connect/logout}
  redirect:
    uri: ${KEYCLOACK_REDIRECT_URI:http://localhost:3000}
  client:
    id: ${KEYCLOACK_CLIENT_ID:sosanimais-client}
    secret: ${KEYCLOACK_CLIENT_SECRET:1234}

fileUploadPath: ${FILE_UPLOAD_PATH:/opt/sosfiles/}
enableHttpsUrl: ${ENABLE_HTTPS_URL:false}
app:
  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost
      - https://sosnovahartz.com.br
      - https://homologacao.sosnovahartz.com.br
telegram:
  bot-token: ${TELEGRAM_BOT_TOKEN:teste}
  chat-id: ${TELEGRAM_CHAT_ID:teste}
  habilitar-telegram: ${TELEGRAM_HABILITAR:false}