server:
  port: 8081
  servlet:
    context-path: /api
spring:
  application:
    name: "Sistema de Gestao SOS Animais"
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/sosanimais}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOACK_URL:http://192.168.2.173:8080}/realms/${KEYCLOACK_REALM:sosanimais-realm}
          jwk-set-uri: ${KEYCLOACK_URL:http://192.168.2.173:8080}/realms/${KEYCLOACK_REALM:sosanimais-realm}/protocol/openid-connect/certs

keycloak:
  url: ${KEYCLOACK_URL_AUTH:http://localhost:8080/realms/sosanimais-realm/protocol/openid-connect/auth}
  token:
    url: ${KEYCLOACK_TOKEN_URL:http://localhost:8080/realms/sosanimais-realm/protocol/openid-connect/token}
  logout:
    url: ${KEYCLOACK_LOGOUT_URL:http://localhost:8080/realms/sosanimais-realm/protocol/openid-connect/logout}
  redirect:
    uri: ${KEYCLOACK_REDIRECT_URI:http://localhost:3000}
  client:
    id: ${KEYCLOACK_CLIENT_ID:sosanimais-client}
    secret: ${KEYCLOACK_CLIENT_SECRET:1234}


fileUploadPath: ${FILE_UPLOAD_PATH:/opt/sosfiles/}