spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/sosanimais}
    username: ${DATABASE_USERNAME:postgres}
    password: ${DATABASE_PASSWORD:postgres}

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    defer-datasource-initialization: true
#    open-in-view: false

  sql:
    init:
      mode: always
  security:
    oauth2:
      resourceserver:
        jwt:
           issuer-uri: ${KEYCLOACK_URL:http://localhost:8080}/realms/sosanimais-realm
           jwk-set-uri: ${KEYCLOACK_URL:http://localhost:8080}/realms/sosanimais-realm/protocol/openid-connect/certs
