name: Deploy no Raspberry

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3
      - name: Configurar Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Build do Backend (Spring Boot)
        run: |
          cd backend
          ./mvnw clean package
          mv target/*.jar app.jar

      - name: Build do Frontend
        run: |
          cd frontend
          npm install
          npm run build

      - name: Copiar backend (JAR) via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: pi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/app.jar"
          target: "/home/pi/app-temp/backend"

      - name: Copiar frontend (build) VIA SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: pi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/build"
          target: "/home/pi/app-temp/frontend"

      - name: Mover arquivos para /opt/app/ e reiniciar backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: pi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /opt/app/back /opt/app/front
            sudo mv /home/pi/app-temp/backend/app.jar /opt/app/back/
            sudo rm -rf /opt/app/front/*
            sudo mv /home/pi/app-temp/frontend/build/* /opt/app/front/
            
            sudo pkill -f 'java -jar' || true
            nohup sudo java -jar /opt/app/back/app.jar > /opt/app/back/backend.log 2>&1 &
            echo "Backend reiniciado!"
