name: Deploy no Raspberry

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Build do Backend (Spring Boot com Maven Wrapper)
        run: |
          cd backend
          ./mvnw clean package -DskipTests
          mv target/*.jar app.jar

      - name: Build do Frontend (React ou Angular)
        run: |
          cd frontend
          npm install
          npm run build

      - name: Copiar backend (JAR) para o Raspberry via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: pi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "backend/app.jar"
          target: "/home/pi/app-temp/backend"

      - name: Copiar frontend (build) para o Raspberry via SSH
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: pi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "frontend/build"
          target: "/home/pi/app-temp/frontend"

      - name: Mover arquivos para /opt/app/ e reiniciar backend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: pi
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /opt/app/back /opt/app/front
            sudo mv /home/pi/app-temp/backend/app.jar /opt/app/back/
            sudo rm -rf /opt/app/front/*
            sudo mv /home/pi/app-temp/frontend/build/* /opt/app/front/

            # Reiniciar o backend
            sudo pkill -f 'java -jar' || true
            nohup sudo java -jar /opt/app/back/app.jar > /opt/app/back/backend.log 2>&1 &
            echo "Backend reiniciado!"
